CREATE DATABASE PROJETO_HOTEL;

USE PROJETO_HOTEL;

CREATE TABLE HOTEL(
    ID_HOTEL INT PRIMARY KEY AUTO_INCREMENT,
	NOME_HOTEL VARCHAR(100) not null,
	CNPJ_HOTEL CHAR(14) not null,
	TELEFONE_HOTEL VARCHAR(30) not null,
	ENDERECO_HOTEL VARCHAR(200) not null
   );
   
CREATE TABLE FUNCIONARIO(
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
	ID_HOTEL INT not null,
	LOGIN VARCHAR(255),
    SENHA VARCHAR(255),
	NOME_FUNCIONARIO VARCHAR(100) not null,
	IDADE_FUNCIONARIO INT,
	RG_FUNCIONARIO VARCHAR(14) not null,
	CPF_FUNCIONARIO VARCHAR(14) not null,
	CTPS_FUNCIONARIO CHAR(14) not null,
	TELEFONE_FUNCIONARIO VARCHAR(30) not null
   );
   
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_HOTEL_ID FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL);
   
CREATE TABLE QUARTO(
    ID_QUARTO INT PRIMARY KEY AUTO_INCREMENT,
	ID_HOTEL INT not null,
	NUMERO_QUARTO INT(4) not null,
	VALOR_DIARIA FLOAT(10,2) not null,
	STATUS_QUARTO INT(1) not null,
	TELEFONE_QUARTO VARCHAR(30)
   );
   
ALTER TABLE QUARTO ADD CONSTRAINT FK_QUARTO_HOTEL_ID FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL);
   
CREATE TABLE HOSPEDE(
    ID_HOSPEDE INT PRIMARY KEY AUTO_INCREMENT,
	NOME_HOSPEDE VARCHAR(100) not null,
	IDADE_HOSPEDE INT,
	RG_HOSPEDE VARCHAR(14) not null,
	CPF_HOSPEDE VARCHAR(14) not null,
	TELEFONE_HOSPEDE VARCHAR(30) not null
   );
   
CREATE TABLE TIPO_PAGAMENTO(
    ID_TIPO_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO_TIPO_PAGAMENTO VARCHAR(100) not null
   );
   
CREATE TABLE RESERVA(
    ID_RESERVA INT PRIMARY KEY AUTO_INCREMENT,
	ID_HOTEL INT not null,
	ID_QUARTO INT not null,
	ID_HOSPEDE INT not null,
	ID_TIPO_PAGAMENTO INT not null,
	ID_FUNCIONARIO INT not null,
	DATA_INICIO DATE not null,
	DATA_FIM DATE not null,
	VALOR_TOTAL FLOAT(10,2) not null
   );
   
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_HOTEL_ID FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_QUARTO_ID FOREIGN KEY (ID_QUARTO) REFERENCES QUARTO (ID_QUARTO);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_TIPO_PAGAMENTO_ID FOREIGN KEY (ID_TIPO_PAGAMENTO) REFERENCES TIPO_PAGAMENTO (ID_TIPO_PAGAMENTO);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_FUNCIONARIO_ID FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_HOSPEDE_ID FOREIGN KEY (ID_HOSPEDE) REFERENCES HOSPEDE(ID_HOSPEDE);


INSERT INTO `hotel` (`ID_HOTEL`, `NOME_HOTEL`, `CNPJ_HOTEL`, `TELEFONE_HOTEL`, `ENDERECO_HOTEL`) VALUES ('1', 'Teste', '12341234123456', '1234', 'Rua algum lugar, apenas teste, ap 52');


INSERT INTO `funcionario` (`ID_FUNCIONARIO`, `ID_HOTEL`, `LOGIN`, `SENHA`, `NOME_FUNCIONARIO`, `IDADE_FUNCIONARIO`, `RG_FUNCIONARIO`, `CPF_FUNCIONARIO`, `CTPS_FUNCIONARIO`, `TELEFONE_FUNCIONARIO`) VALUES ('1', '1', 'lucas', '1234', 'Lucas', '20', '1234', '1234', '1234', '1234');


STR_TO_DATE(?,GET_FORMAT(DATE,'BRA'));